language: python
python:
  - 2.6
  - 2.7
  - pypy

install:
  # Build/test dependencies
  - python setup.py install
  - sudo apt-get -y install pylint

script:
  - pylint --rcfile=.pylintrc *.py && python namebench.py

notifications:
  email: false
